Dev-FE-1/Toy_Project_2_Team1

.eslintrc.cjs
src/App.tsx

import 절대경로 오류를 수정했습니다.
closes #25 
- 'import/no-unresolved': 'off' 설정

[fix] import 절대경로 오류 수정

---

src/components/common/Button.tsx

[fix] 버튼 컴포넌트 절대경로로 수정

---

package-lock.json
package.json
src/components/common/Select.tsx

Select 컴포넌트 추가했습니다!
state는 컴포넌트를 사용하는 쪽에서 관리하는게 재활용하기 편할 것 같아서 options, selected, onChange를 받아올 수 있도록 만들었습니다
closes #15 
- Select 컴포넌트 추가
- 선택된 option에 background 컬러 적용
- Headless UI 패키지 추가했습니다!
사용 예시
```ts
import Select from '@/components/common/Select';
const selectOptions = ['연장 근무', '휴일 근무', '무급 휴가', '기타'];
const HomePage = () => {
const [selectedOption, setSelectedOption] = useState(selectOptions[0]);
return (
<div>
<Select options={selectOptions} selected={selectedOption} onChange={setSelectedOption} />
</div>
);
};
```

[feat] Select 컴포넌트 추가

---

src/components/common/Badge.tsx

Badge 컴포넌트 추가했습니다!
closes #16 
Badge 컴포넌트 추가
사용 방법
```tsx
import Badge from '@/components/common/Badge';
const HomePage = () => (
<>
<Badge color='red' label='반려' />
<Badge color='orange' label='실수령액' />
<Badge color='green' label='승인' />
<Badge color='gray' label='대기' />
</>
);
```

[feat] Badge 컴포넌트 추가

---

src/components/common/IconButton.tsx

closes #5 
```tsx
// 사용방법
import IconTextButton from '@/components/common/IconButton';
const HomePage = () => (
<>
<IconTextButton label='저장' styleType='save' />
<IconTextButton label='파일 추가' styleType='addFile' />
<IconTextButton label='수정' styleType='edit' />
<IconTextButton label='프로필 수정' styleType='edit' />
</>
);
export default HomePage;
```

[Feat] 텍스트가 있는 아이콘버튼 컴포넌트 추가

---

src/components/common/Tabs.tsx
src/pages/Salary.tsx

탭 컴포넌트 추가
closes #12 
- 탭 컴포넌트 추가
- Salary.tsx 내용 추가

[feat] Tabs 컴포넌트 추가

---

src/components/common/Spinner.tsx

로딩 스피너 추가
closes #45
로딩 스피너 추가했습니다!

[feat] 로딩스피너 추가

---

src/components/common/Input.tsx
src/pages/Profile.tsx

Input 컴포넌트 추가 
closes #08
인풋 컴포넌트 추가

[feat] input 컴포넌트 추가

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/refactor.yml
src/components/common/Modal.tsx

모달 컴포넌트 추가
closes #10
모달 컴포넌트 추가

[feat] Modal 컴포넌트 추가

---

src/components/common/Buttons/Button.tsx

closes #51 
버튼 안쪽에 아이콘 및 텍스트 중앙정렬 되도록 변경

[fix] 버튼 안쪽에 중앙 정렬 하기

---

src/components/common/Modal.tsx

모달 컴포넌트 수정 완료
closes #52 
onClose 함수를 모달 컴포넌트 안에서 다루기
cancelText 기본값 '취소'로 설정
variant 제거
z-index 적용
버튼 경로 수정

[refactor] 모달 컴포넌트 수정

---

src/components/common/SalaryCard.tsx
src/components/common/Tabs.tsx
src/components/dashboard/PayrollNotice.tsx
src/pages/Salary.tsx

급여명세서 알림 컴포넌트 추가
closes #56
- 급여 명세서 알림 컴포넌트 구현
- tab 컴포넌트 제목 간격 수정
- Salary.tsx에 렌더링
- dashboard 폴더 추가

[feat] 급여명세서 알림 컴포넌트 추가

---

src/constants/api.ts

closes #64 
interface ImportMeta를 사용하여 env 변수 정의

[fix] importMeta를 사용하여 환경 변수를 정의

---

src/api/User.ts
src/api/index.ts
src/types/type.ts

closes #61 
현재 로그인한 유저의 uid로 firebase 의 User collection에서 쿼리를 날려 가져오는 코드 작성
테스트했던 Profile.tsx 코드 첨부드립니다.
- 테스트 코드여서 3개 데이터만 가져와서 확인해봤습니다.
- 테스트방법: 로그인: kimth@studiot.com / test1234! -> 프로필탭 이동
<details>
<summary>Profile.tsx 코드 확인</summary>
```typescript
import { useEffect, useState } from 'react';
import { Timestamp } from 'firebase/firestore';
import { auth } from '@/api';
import { getUserData } from '@/api/User';
import Input from '@/components/common/Input';
import { UserType } from '@/types/type';
const InitUserData: UserType = {
uid: '',
userNo: 0,
name: '',
nickname: '',
email: '',
hireDate: new Timestamp(0, 0),
birthday: new Timestamp(0, 0),
img: '',
phone: '',
team: '',
position: '',
};
const ProfilePage = () => {
const [userInfo, setUserInfo] = …
```

[feat] firebase 유저정보 연동

---

src/components/common/Tabs.tsx
src/components/dashboard/PayrollList.tsx
src/pages/Salary.tsx

급여명세서 목록 컴포넌트 추가
closes #65 
- 급여명세서 목록 컴포넌트 구현
- 탭 컴포넌트 스타일 수정
- Salary.tsx에 렌더링
금액 색상 바꿔봤는데 어떠신가요?

[feat] 급여명세서 목록 컴포넌트 추가

---

package-lock.json
src/components/Calendar/Calendar.tsx
src/components/common/Tabs.tsx
src/constants/colors.ts
src/hooks/useFetchSchedule.ts
src/pages/Schedule.tsx
src/store/hooks.ts
src/store/reducer/scheduleSlice.ts
src/store/store.ts
src/styles/GlobalStyle.tsx
src/types/api.ts
src/types/schedule.ts
src/utils/schedule.ts

schedule reducer를 만들고 firebase에서 실제 데이터를 불러와 calendar 데이터를 실제 데이터로 변경했습니다.
- scheduleReducer 추가
- useFetchSchedule hook 추가
- Calendar 더미 데이터를 실제 데이터로 변경
package.lock.json 이슈가 있는 것 같아 삭제하고 다시 설치했습니다
`package.lock.json` 파일과 `node_modules` 폴더 삭제 후 pull 받으신 다음 `npm install` 해보시면 될 것 같아요!

[feat] Schedule Reducer 생성 및 firebase로 실제 데이터 불러오기

---

src/components/common/Buttons/Button.tsx
src/components/common/Input.tsx

closes #83 
Input 컴포넌트의 name값을 추가
Button의 style이 disabled 일 경우 클릭 안되게 disabled 속성 추가

[refactor] 컴포넌트 사용성 개선 

---

src/App.tsx
src/constants/path.ts
src/pages/PayrollDetail.tsx

closes #88 
라우터 children 코드 수정
path.ts 코드 수정

[fix] 라우터 오류 수정

---

src/pages/Profile.tsx

일단 임시로 Profile 페이지 스타일 수정했는데 나중에 추가 수정 필요할 것 같아요!
- Profile 페이지 스타일 수정

[design] Profile 페이지 스타일 수정

---

src/components/payroll/CorrectionForm.tsx
src/pages/Salary.tsx

closes #i111
- ui 구현
- 제목, 사유 미입력시 버튼 비활성화
- 파일 첨부 기능 추가
- 신청일 오늘 날짜에 맞게 자동으로 설정
제출 기능 구현은 조금 기다려주세용..

[feat] 정정 신청 페이지 추가

---

src/components/common/Toast.tsx
src/hooks/useToast.ts
src/layouts/Root.tsx
src/store/reducer/toastSlice.ts
src/store/store.ts
src/types/api.d.ts

closes #127 
- 토스트 커스텀 훅 제작
- 사용법: 
토스트메세지를 띄우고 싶은 곳에서
```typescript
const { toastTrigger } = useToast();
toastTrigger('토스트메세지'); 
``` 
위 코드를 호출하면 토스트메세지가 출력됩니다.
- 지금 개발사항으로는 토스트메세지는 1개씩만 출력됩니다.
- 아래 코드를 Home.tsx에 적용하고 테스트버튼을 클릭하면 profile페이지로 이동하면서 토스트 메세지가 출력됩니다.
<details><summary> :pray: 테스트코드: Home.tsx :pray: </summary>
```typescript
import { css } from '@emotion/react';
import logoIcon from '@/assets/images/logo_icon.svg';
import PayrollNotice from '@/components/dashboard/PayrollNotice';
import UpcomingSchedules from '@/components/dashboard/UpcomingSchedules';
import theme from '@/styles/theme';
import { UpcomingType } from '@/types/type';
import Button from '@/components/common/buttons/Button';
import useToast from '@/hooks/useToast';
import { useNavigate } from …
```

[feat] 토스트메세지 커스텀 훅 개발

---

src/pages/DailyScheduleDetail.tsx
src/store/reducer/scheduleSlice.ts

[fix] userNo를 이용한 일정 조회

---

src/components/common/Input.tsx
src/components/common/Spinner.tsx
src/pages/SignIn.tsx

로그인 페이지 스타일 수정했습니다
- 로그인페이지 스타일 수정
- input 스타일 수정
- spinner 스타일 수정

[design] 로그인 페이지 스타일 수정

---

src/components/common/Modal.tsx
src/components/dashboard/UpcomingSchedules.tsx
src/pages/Home.tsx

홈페이지에 오늘의 일정 컴포넌트 추가했습니다
- 홈페이지에 오늘의 일정 컴포넌트 추가
- 약간의 스타일 수정

[feat] home 페이지에 오늘의 일정 컴포넌트 추가

---

src/pages/Profile.tsx
src/pages/ProfileEdit.tsx

프로필 페이지 - 정보 수정, 사진 삭제, 스피너 추가 완료
closes #148 
DB에 닉네임, 전화번호 수정 
storage에 사진 업로드하고 수정버튼 클릭시 DB 반영
UID 고정값으로 우선 작업 - 금일 멘토링 이후 수정 예정. 

[Feat] 프로필 페이지 구현 #148

---

src/api/common.ts
src/api/payroll.ts
src/api/schedule.ts
src/components/common/buttons/IconTextButton.tsx
src/components/payroll/CorrectionForm.tsx
src/constants/api.ts
src/store/reducer/payrollSlice.ts
src/store/store.ts
src/types/api.d.ts
src/types/payroll.d.ts
src/utils/auth.ts
src/utils/dailySchedule.ts

[feat] 정정신청 api 연동

---

src/api/schedule.ts
src/api/user.ts
src/components/common/DatePicker.tsx
src/components/scheduleForm/ScheduleForm.tsx
src/pages/Profile.tsx
src/pages/ScheduleAdd.tsx
src/store/reducer/scheduleSlice.ts
src/types/api.d.ts
src/types/type.d.ts
src/utils/auth.ts

closes #155 
- 일정 등록 api 연동
- profile 로그아웃버튼 수정

[feat] 일정등록 api 연동

---

src/api/payroll.ts
src/api/schedule.ts
src/store/reducer/scheduleSlice.ts
src/utils/auth.ts

closes #160 
getUID를 불러올때 auth.getAuthStateReady()를 호출, 준비 된 후 auth.currentUser.uid 를 가져오도록 변경했습니다.
getUID는 await를 붙여서 사용해주세요

[fix] getUID 비동기처리 

---

src/pages/Profile.tsx
src/pages/ProfileEdit.tsx

개인 로그인 시, 개인 정보로 호출 및 정보 변경 가능
closes #159

[feat] 프로필 UID 연결 (#159)

---

src/pages/NotFound.tsx

[feat] 404 페이지 추가 

---

src/components/dashboard/CompanySchedules.tsx
src/mock/data.ts
src/pages/Home.tsx
src/types/type.d.ts

closes #154 
- 회사일정 컴포넌트 개발
- mockData 분리 '@/mock/data.ts'

[feat] 회사일정 컴포넌트 개발

---

src/api/common.ts
src/api/payroll.ts
src/components/common/Toast.tsx
src/components/payroll/CorrectionForm.tsx
src/components/payroll/CorrectionHistory.tsx
src/pages/CorrectionDetail.tsx
src/pages/CorrectionEdit.tsx
src/store/reducer/payrollSlice.ts

#161 
- 신청, 수정, 삭제 기능 추가
- 정정 내역 날짜순으로 배치(색인 생성)
- 대기 상태에서만 수정, 삭제되게 설정
- 신청하면 정정내역으로 이동
- 토스트 메시지 스타일 수정
- 모달, 토스트 설정
- 첨부파일 표시 스타일 수정,
- 첨부파일 삭제 기능 추가
- 어긋난 스타일 전체 수정
불태웠습니다..

[feat] 정정페이지 완료

---

src/pages/PayrollDetail.tsx

closes #171
급여명세서 저장된 이미지에서 저장 버튼 제거

[feat] 급여명세서 저장된 이미지에서 저장 버튼 제거

---

src/pages/CorrectionDetail.tsx
src/pages/DailyScheduleDetail.tsx
src/pages/Profile.tsx
src/store/reducer/scheduleSlice.ts

closes #175 
- 일정 삭제 후 redux state 변경
- 일정 상세보기 -> 수정버튼 navigate 추가
- 정정내역 상세보기 -> 첨부파일 없는데 클릭됨
- 로그아웃했을때 isfetched = false로 설정
추가작업 필요
- 월급 조회하기 컴포넌트 빤짝이는 현상
-  정정내역 수정할때 첨부파일 경로 api연동
- 급여명세서 컴포넌트 조회하기 버튼 - 2024-7 -> 2024-07 로 데이터 변경해주기

[refactor] 최종 회의 중 발생한 문제 수정

---

src/components/dashboard/PayrollNotice.tsx
src/pages/CorrectionDetail.tsx
src/pages/CorrectionEdit.tsx
src/pages/PayrollDetail.tsx

- 급여명세서 컴포넌트 조회하기 버튼 - 2024-7 -> 2024-07 로 데이터 변경해주기
- 정정내역 수정할때 첨부파일 경로 api연동

[refactor] 최종테스트 중 발견한 사항 수정 누락부분
